apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-deployment
  namespace: taskapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskapi
  template:
    metadata:
      labels:
        app: taskapi
    spec:
      containers:
        - name: taskapi
          image: kanchana20/taskapi:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
