apiVersion: v1
kind: Service
metadata:
  name: task-api-service
  namespace: taskapi
spec:
  selector:
    app: taskapi
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30091